### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by luanfreitasdev** [pestphp/pest-intellij#105]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 0.4.2
| Pest version     | x.y.z
| OS               | Windows 10

### Stacktrace
```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:177)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:143)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:105)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:59)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:201)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:216)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:937)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:744)
	at com.pestphp.pest.PestUtilKt.isPestTestFile(PestUtil.kt:16)
	at com.pestphp.pest.PestIconProvider.getIcon(PestIconProvider.kt:10)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:87)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:83)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:83)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:43)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:282)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:169)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:101)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:169)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress
```

**Comment by olivernybroe** [comment]
@luanfreitasdev Thanks for reporting this, could you please add some more information? 

- Did you do anything in specific for getting this error? 
- What version of PhpStorm/IntelliJ Ultimate did you use? (have to add that to the template)
- What is not working when you get this error?

**Comment by luanfreitasdev** [comment]
Hello @olivernybroe , this bug was reported directly from phpstorm, but it has not appeared.

version 2020.3.2

**Comment by olivernybroe** [comment]
Will be in next EAP
