### ISSUE TITLE
java.lang.Exception in PhpStorm 2021.1

### ISSUE THREAD

**Issue by manuglopez** [pestphp/pest-intellij#117]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 0.4.3
| Pest version     | x.y.z
| IntelliJ version | PS-211.6693.120
| OS               | Linux

### Stacktrace
```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:168)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:134)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:101)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:235)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:60)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:202)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:150)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:210)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:730)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:933)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:740)
	at com.pestphp.pest.PestUtilKt.isPestTestFile(PestUtil.kt:19)
	at com.pestphp.pest.PestIconProvider.getIcon(PestIconProvider.kt:15)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:88)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:84)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:84)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:299)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:185)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:110)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtil
```

**Comment by olivernybroe** [comment]
Thanks for reporting this bug, could you provide a bit more information? 

Do you know how to reproduce it?
Is it spamming you with this error?
Is there anything that looks broken?

**Comment by manuglopez** [comment]
I have installed a package and run php-cs-fixer. It seems that had to be with some cached by phpstorm( probably two files that were in the project and now are deleted)  because error has disappeared, after running same command again. I could not reproduce it again. Sorry for the lack of accurate information.

**Comment by olivernybroe** [comment]
It's okay 👍 Thanks for reporting it, would rather have people reporting issues with lack of information, then not reporting it. 

Now we have this issue on GitHub, meaning if others experience it, it will show up on Google and we might find a way to reproduce.
