### ISSUE TITLE
java.lang.UnsupportedOperationException: This PHP type is immutable

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#118]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 0.4.4-EAP.1
| IntelliJ version | PS-211.7036.8
| OS               | Mac OS X

### Description
This error happened when trying to use the go to test hotkey on a class where no tests exists.

### Stacktrace
```
java.lang.UnsupportedOperationException: This PHP type is immutable
	at com.jetbrains.php.lang.psi.resolve.types.PhpType$ImmutablePhpType.getException(PhpType.java:1097)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType$ImmutablePhpType.add(PhpType.java:1083)
	at com.pestphp.pest.types.ExpectExtendTypeProvider.complete(ExpectExtendTypeProvider.kt:56)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:156)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:156)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:113)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:92)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:657)
	at com.jetbrains.php.lang.psi.elements.PhpTypedElement.getGlobalType(PhpTypedElement.java:53)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.classHasTraitUseRules(PhpCodeInsightUtil.java:2150)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.mayHaveRefParams(PhpCodeInsightUtil.java:2136)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.isPassByRefParameter(PhpCodeInsightUtil.java:2069)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.isWriteAccess(VariableImpl.java:236)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl$DeclarationCollector.visitPhpVariable(VariableImpl.java:740)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.accept(VariableImpl.java:131)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.visitors.PhpRecursiveElementVisitor.visitElement(PhpRecursiveElementVisitor.java:42)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl$DeclarationCollector.visitElement(VariableImpl.java:695)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpElement(PhpElementVisitor.java:38)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpParameterList(PhpElementVisitor.java:90)
	at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:105)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.jetbrains.php.lang.psi.visitors.PhpRecursiveElementVisitor.visitElement(PhpRecursiveElementVisitor.java:42)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl$DeclarationCollector.visitElement(VariableImpl.java:695)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpElement(PhpElementVisitor.java:38)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpMethodReference(PhpElementVisitor.java:122)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:38)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
```

**Comment by olivernybroe** [comment]
Problem should have been solved in the newest EAP 
[PEST PHP-0.4.4-EAP.1.zip](https://github.com/pestphp/pest-intellij/files/6389581/PEST.PHP-0.4.4-EAP.1.zip)
