### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by cb400sp2** [pestphp/pest-intellij#130]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 0.4.3
| Pest version     | x.y.z
| IntelliJ version | PS-211.7442.50
| OS               | Mac OS X

### Stacktrace
```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:168)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:134)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:101)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:235)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:60)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:202)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:150)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:210)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:730)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:933)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:740)
	at com.pestphp.pest.PestUtilKt.isPestTestFile(PestUtil.kt:19)
	at com.pestphp.pest.PestIconProvider.getIcon(PestIconProvider.kt:15)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:88)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:84)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:84)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:299)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:185)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:110)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtil
```

**Comment by olivernybroe** [comment]
@cb400sp2 Thanks for reporting the bug, could you please add some details on when this happens or share the file it happens in?

**Comment by cb400sp2** [comment]
This happened when I tried to switch git branches and manipulate files.

**Comment by dingo-d** [comment]
The same happened to me just moments ago, and the odd thing is the project I'm working on doesn't use pest, and I didn't do anything in the IDE

<details>
<summary>Error log</summary>
<code>
<pre>
Outdated stub in index: file://Z:/home/dzoljom/Sites/Client/project/wp-content/themes/project/src/Blocks/Blocks.php indexing timestamp = 1625483924581, binary = false, byte size = 7401, char size = 7401, doc=DocumentImpl[file://Z:/home/dzoljom/Sites/Client/project/wp-content/themes/project/src/Blocks/Blocks.php], docSaved=true, wasIndexedAlready=true, queried at 1625483924581
doc length=6652
file length=6652
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
projects with file: 1
physical file exists; length = 6652

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:168)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:134)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:101)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:235)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:60)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:202)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:150)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:210)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:730)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:933)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:740)
	at com.pestphp.pest.PestUtilKt.isPestTestFile(PestUtil.kt:19)
	at com.pestphp.pest.PestIconProvider.getIcon(PestIconProvider.kt:15)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:88)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:84)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:84)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:299)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:185)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:110)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:100)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
</pre>
</code>
</details>

PhpStorm details

```PhpStorm 2021.1.4
Build #PS-211.7628.25, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2038M
Cores: 16
Registry: debugger.watches.in.variables=false, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic (4.1.7), com.intellij.ideolog (203.0.27.0), com.mallowigi (36.0), zielu.gittoolbox (203.5.10), name.kropp.intellij.makefile (211.7628.1), com.intellij.plugins.html.instantEditing (211.6693.111), com.laravel_idea.tailwind (1.3.0), com.dmarcotte.handlebars (211.6693.44), NEON support (0.5.1), com.chrisrm.idea.MaterialThemeUI (6.7.2), de.espend.idea.laravel (0.15.4), com.pestphp.pest-intellij (0.4.3), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.210), ru.adelf.idea.dotenv (2021.2)
```

**Comment by olivernybroe** [comment]
Thanks, having some hard time reproducing, but might be able to catch the error and ignore it when it happens. 

It should be fine based on the error message 🙂

**Comment by dingo-d** [comment]
Yeah, it happens super randomly 🤷‍♂️

But it doesn't seem to affect the functionality of the IDE.

I think it could be related to wsl2 somehow, because I didn't notice these errors on mac...

**Comment by olivernybroe** [comment]
@dingo-d Ah that might make sense. We will def. just silence the error then 👍 

My theory is that this is related to the indexing phpstorm does getting out of date when files were changed after running a command which is not part of phpstorm
