### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.

### ISSUE THREAD

**Issue by Jamesking56** [pestphp/pest-intellij#148]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.1
| Pest version     | N/A
| IntelliJ version | PS-212.4746.100
| OS               | Mac OS X

### Description

This happened in a project we haven't converted to Pest yet, using Laravel PHPUnit.

### Stacktrace
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PHP file, file.class=class com.jetbrains.php.lang.psi.PhpFileImpl, file.lang=Language: PHP, modStamp=10
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
latestIndexedStub=null
 viewProvider=com.jetbrains.php.lang.PhpFileViewProvider{vFile=file:///Users/jamesking56/PhpstormProjects/{SNIP}/tests/Feature/Draft/CreateDraftTest.php, vFileId=604, content=VirtualFileContent{size=2994}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1626987522295; file length: 2994
 doc saved: true; doc stamp: 0; doc size: 0; committed: true
indexing info: null
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:242)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:240)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:61)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:212)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:731)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:934)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:741)
	at com.pestphp.pest.ExpectUtilKt.getExpectExtends(ExpectUtil.kt:85)
	at com.pestphp.pest.fileListeners.ExtendAsyncFileListener.updateFile(ExtendAsyncFileListener.kt:35)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$processRecursively$1.visitFile(AsyncFileChangeListenerBase.kt:59)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:108)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:293)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:317)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase.processRecursively(AsyncFileChangeListenerBase.kt:56)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase.process(AsyncFileChangeListenerBase.kt:
```

**Comment by olivernybroe** [comment]
Thanks for reporting and adding details! I'll look into it and find a fix.

Is it spamming you with this error or is it only happening once?

**Comment by Jamesking56** [comment]
It happened once after updating to the new PHPStorm 2021.2, but the project didn't have Pest installed.

**Comment by olivernybroe** [comment]
Alright, the issue seems like it actually is a phpstorm bug, however I'll see if I can disable this listener if pest is not installed and silence the exception from phpstorm
