### ISSUE TITLE
java.lang.Throwable: It's prohibited to access index #php.meta.type.inference.mapping during event dispatching

### ISSUE THREAD

**Issue by iksaku** [pestphp/pest-intellij#150]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.1
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Mac OS X

### Description
Running test suite with 1 test being skipped, rest are run using named datasets.

### Stacktrace
```
java.lang.Throwable: It's prohibited to access index #php.meta.type.inference.mapping during event dispatching
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:32)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:27)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:758)
	at com.intellij.util.indexing.FileBasedIndexEx.ensureUpToDate(FileBasedIndexEx.java:449)
	at com.intellij.util.indexing.FileBasedIndexEx.getIndexModificationStamp(FileBasedIndexEx.java:230)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTableProviderImpl.lambda$getModificationTracker$1(PhpMetaTableProviderImpl.java:46)
	at com.intellij.util.CachedValueBase.getTimeStamp(CachedValueBase.java:145)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:132)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:124)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:114)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.checkUpToDate(CachedValueBase.java:97)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:93)
	at com.intellij.psi.impl.PsiCachedValueImpl.getUpToDateOrNull(PsiCachedValueImpl.java:13)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:63)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTableProviderImpl.getTable(PhpMetaTableProviderImpl.java:21)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTypeInferenceMappingIndex.getMap(PhpMetaTypeInferenceMappingIndex.java:82)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.lambda$getStaticMethodTypesMap$15(PhpParameterBasedTypeProvider.java:472)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getStaticMethodTypesMap(PhpParameterBasedTypeProvider.java:470)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getType(PhpParameterBasedTypeProvider.java:583)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.complete(PhpParameterBasedTypeProvider.java:574)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:163)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:163)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:120)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:99)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:684)
	at com.pestphp.pest.services.ExpectationFileService.updateExtends(ExpectationFileService.kt:40)
	at com.pestphp.pest.fileListeners.ExtendAsyncFileListener.updateFile(ExtendAsyncFileListener.kt:46)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$processRecursively$1.visitFile(AsyncFileChangeListenerBase.kt:59)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:108)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:293)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase.processRecursively(AsyncFileChangeListenerBase.kt:56)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase.process(AsyncFileChangeListenerBase.kt:44)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase.access$process(AsyncFileChangeListenerBase.kt:12)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$processChangeEvents$7.invoke(AsyncFileChangeListenerBase.kt:101)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$processChangeEvents$7.invoke(AsyncFileChangeListenerBase.kt:12)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$ChangeSeparator.applyBefore(AsyncFileChangeListenerBase.kt:115)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$prepareChange$1.beforeVfsChange(AsyncFileChangeListenerBase.kt:32)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.beforeVfsChange(AsyncEventSupport.java:127)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport$1.before(AsyncEventSupport.java:61)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy159.before(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.fireBeforeEvents(PersistentFSImpl.java:1182)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$3.close(PersistentFSImpl.java:770)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.write(LoadTextUtil.java:450)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:414)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:326)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:403)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:364)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:950)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:93)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:364)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocuments(FileDocumentManagerImpl.java:284)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:259)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:252)
	at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.kt:24)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:799)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by olivernybroe** [comment]
Thanks for reporting! 😄 

Unfortunately the stacktrace here has been cut (because of github limit) and does not contain the code related to pest plugin. 
Would you be able to copy paste the stack trace next time it happens in here so we can see what caused it? 👍

**Comment by iksaku** [comment]
@olivernybroe thanks for the heads up!
Just recovered the error from my logs, updated the issue with the full stack trace 👌

**Comment by olivernybroe** [comment]
@iksaku awesome thanks a bunch! 👍
