### ISSUE TITLE
java.lang.Throwable: It's prohibited to access index #Stubs during event dispatching

### ISSUE THREAD

**Issue by jaetooledev** [pestphp/pest-intellij#156]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.1
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Windows 10

### Description
When adding in a uses() function in Pest.php and chaining in('Unit'), when changing that line I appear to be getting the below constantly. The line of code I am changing is the following:
`uses(Tests\BaseTest::class, RefreshDatabase::class)->in('Unit');`

### Stacktrace
```
java.lang.Throwable: It's prohibited to access index #Stubs during event dispatching
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:32)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:27)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:758)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:501)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:305)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:576)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:994)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:969)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1044)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1081)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:728)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:664)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:174)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:120)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:240)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:759)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:664)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.lambda$getTarget$13(PhpParameterBasedTypeProvider.java:452)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getTarget(PhpParameterBasedTypeProvider.java:452)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getBySignature(PhpParameterBasedTypeProvider.java:267)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:778)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.
```

**Comment by olivernybroe** [comment]
This has actually just been fixed. 
Release is still pending in marketplace, however you can download it manually here
https://github.com/pestphp/pest-intellij/releases/tag/v1.0.2

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>

**Comment by olivernybroe** [comment]
New version is already out https://plugins.jetbrains.com/plugin/14636-pest/versions/stable/130809
