### ISSUE TITLE
java.lang.Throwable: It's prohibited to access index #php.meta.type.inference.mapping during event dispatching

### ISSUE THREAD

**Issue by Lukasss93** [pestphp/pest-intellij#157]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.2
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Windows 10

### Description
PHPStorm Exception:
java.lang.Throwable: It's prohibited to access index #php.meta.type.inference.mapping during event dispatching

### Stacktrace
```
java.lang.Throwable: It's prohibited to access index #php.meta.type.inference.mapping during event dispatching
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:32)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:27)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:758)
	at com.intellij.util.indexing.FileBasedIndexEx.ensureUpToDate(FileBasedIndexEx.java:449)
	at com.intellij.util.indexing.FileBasedIndexEx.getIndexModificationStamp(FileBasedIndexEx.java:230)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTableProviderImpl.lambda$getModificationTracker$1(PhpMetaTableProviderImpl.java:46)
	at com.intellij.util.CachedValueBase.getTimeStamp(CachedValueBase.java:145)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:132)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:124)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:114)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.checkUpToDate(CachedValueBase.java:97)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:93)
	at com.intellij.psi.impl.PsiCachedValueImpl.getUpToDateOrNull(PsiCachedValueImpl.java:13)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:63)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTableProviderImpl.getTable(PhpMetaTableProviderImpl.java:21)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTypeInferenceMappingIndex.getMap(PhpMetaTypeInferenceMappingIndex.java:82)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.lambda$getStaticMethodTypesMap$15(PhpParameterBasedTypeProvider.java:472)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(C
```

**Comment by olivernybroe** [comment]
Hmm, could you get a stacktrace for me next time? GitHub limits the characters so the full stacktrace is not there and cannot see the pest related stuff in there.

**Comment by olivernybroe** [comment]
Should have been resolved now in
https://github.com/pestphp/pest-intellij/releases/tag/v1.0.3
It is still pending approval in marketplace, however you can install it manually.

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
