### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by hsmfawaz** [pestphp/pest-intellij#172]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.5
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Linux

### Stacktrace
```
java.lang.NullPointerException
	at com.pestphp.pest.PestIconProvider.getIcon(PestIconProvider.kt:27)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:88)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:84)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:84)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:297)
	at com.intellij.diagram.components.ScalableIconWrapper.evaluateDeferred(ScalableIconWrapper.java:112)
	at com.intellij.diagram.components.ScalableIconWrapper.evaluateDeferredAndWrap(ScalableIconWrapper.java:106)
	at com.intellij.diagram.components.DiagramNodeHeaderComponent.createLabel(DiagramNodeHeaderComponent.java:45)
	at com.intellij.diagram.components.DiagramNodeHeaderComponent.<init>(DiagramNodeHeaderComponent.java:36)
	at com.intellij.diagram.components.DiagramNodeContainer.<init>(DiagramNodeContainer.java:133)
	at com.intellij.diagram.extras.DiagramExtras.createNodeComponent(DiagramExtras.java:123)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.lambda$tuneNode$3(DefaultUmlRenderer.java:69)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.tuneNode(DefaultUmlRenderer.java:67)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.tuneNode(DefaultUmlRenderer.java:59)
	at com.intellij.openapi.graph.builder.renderer.AbstractColoredNodeCellRenderer.getRendererComponent(AbstractColoredNodeCellRenderer.java:57)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.getRendererComponent(DefaultUmlRenderer.java:84)
	at com.intellij.openapi.graph.builder.renderer.BasicNodeCellRenderer.getNodeCellRendererComponent(BasicNodeCellRenderer.java:54)
	at com.intellij.openapi.graph.builder.util.GraphViewUtil.setRenderedNodeSizes(GraphViewUtil.java:163)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.updateNodeRealizer(GraphBuilderImpl.java:266)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.updateRealizers(GraphBuilderImpl.java:255)
	at com.intellij.uml.UmlGraphBuilder.updateRealizers(UmlGraphBuilder.java:244)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.updateView(GraphBuilderImpl.java:239)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.updateGraph(GraphBuilderImpl.java:191)
	at com.intellij.openapi.graph.builder.GraphBuilder.updateGraph(GraphBuilder.java:84)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.a(GraphBuilderImpl.java:134)
	at com.intellij.openapi.application.WriteAction.lambda$runAndWait$2(WriteAction.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithC
```

**Comment by olivernybroe** [comment]
Thanks for reporting this, we are actually in the middle of releasing our next version v.1.1.0 which contains bigger design changes and one of them are actually the icon provider which is failing for you. 

If it keeps happening in the new version, then we will of course re-open this issue.

You can find the latest release under releases tab for download manually or wait until the version has been approved in JetBrains Marketplace.
https://github.com/pestphp/pest-intellij/releases

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>

**Comment by hsmfawaz** [comment]
Thanks so much for your time ,
Have a good day
