### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by iksaku** [pestphp/pest-intellij#177]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.1.0
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Mac OS X

### Description
As soon as it began indexing changes to my project (Updating Pest to v1.16.0), it threw this error.
No test suite was running at the moment of the update and crash, no other actions where present at that moment either.

### Stacktrace
```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:821)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:773)
	at com.intellij.util.indexing.FileBasedIndexEx.ensureUpToDate(FileBasedIndexEx.java:449)
	at com.intellij.util.indexing.FileBasedIndexEx.getIndexModificationStamp(FileBasedIndexEx.java:230)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTableProviderImpl.lambda$getModificationTracker$1(PhpMetaTableProviderImpl.java:46)
	at com.intellij.util.CachedValueBase.getTimeStamp(CachedValueBase.java:145)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:132)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:124)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:114)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.checkUpToDate(CachedValueBase.java:97)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:93)
	at com.intellij.psi.impl.PsiCachedValueImpl.getUpToDateOrNull(PsiCachedValueImpl.java:13)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:63)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTableProviderImpl.getTable(PhpMetaTableProviderImpl.java:21)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpMetaTypeInferenceMappingIndex.getMap(PhpMetaTypeInferenceMappingIndex.java:82)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.lambda$getStaticMethodTypesMap$15(PhpParameterBasedTypeProvider.java:472)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getStaticMethodTypesMap(PhpParameterBasedTypeProvider.java:470)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getType(PhpParameterBasedTypeProvider.java:583)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.complete(PhpParameterBasedTypeProvider.java:574)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:163)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:163)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:120)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:99)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:684)
	at com.pestphp.pest.generators.ExpectationGenerator.methodString(ExpectationGenerator.kt:34)
	at com.pestphp.pest.generators.ExpectationGenerator.access$methodString(ExpectationGenerator.kt:13)
	at com.pestphp.pest.generators.ExpectationGenerator$generate$1.invoke(ExpectationGenerator.kt:18)
	at com.pestphp.pest.generators.ExpectationGenerator$generate$1.invoke(ExpectationGenerator.kt:18)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3344)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3361)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3360)
	at com.pestphp.pest.generators.ExpectationGenerator.generate(ExpectationGenerator.kt:18)
	at com.pestphp.pest.generators.ExpectationGenerator.generateToFile(ExpectationGenerator.kt:44)
	at com.pestphp.pest.services.ExpectationFileService$generateFile$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.pestphp.pest.services.ExpectationFileService.generateFile(ExpectationFileService.kt:117)
	at com.pestphp.pest.fileListeners.ExtendAsyncFileListener.updateFile$lambda-5$lambda-4(ExtendAsyncFileListener.kt:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by olivernybroe** [comment]
Just so people know, I am working on a fix for this. However it requires a big rewrite of one of the features, so it's taking quite a while 👍

**Comment by olivernybroe** [comment]
I have a fix ready in the current EAP. 
I will wait with releasing it until we have had it running in EAP for a while, to make sure the solution actually works for all.

You can install it via the EAP channel or install it manually
https://github.com/pestphp/pest-intellij#installation

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.2.0-EAP.2.zip](https://github.com/pestphp/pest-intellij/files/7234566/PEST.PHP-1.2.0-EAP.2.zip)
