### ISSUE TITLE
java.lang.RuntimeException: java.io.EOFException

### ISSUE THREAD

**Issue by RayhanYulanda** [pestphp/pest-intellij#183]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.3
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Windows 10

### Stacktrace
```
java.lang.RuntimeException: java.io.EOFException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection.handleError(PersistentFSConnection.java:291)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.handleError(FSRecords.java:717)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:262)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.createRecord(FSRecords.java:161)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.makeChildRecord(PersistentFSImpl.java:1557)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.executeCreateChild(PersistentFSImpl.java:1529)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.applyEvent(PersistentFSImpl.java:1445)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvent(PersistentFSImpl.java:831)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.createChildFile(PersistentFSImpl.java:505)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.createChildData(VirtualFileSystemEntry.java:276)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.add(PsiDirectoryImpl.java:408)
	at com.pestphp.pest.services.ExpectationFileService.generateFile$lambda-6$lambda-5$lambda-4(ExpectationFileService.kt:92)
	at com.intellij.openapi.project.DumbServiceHeavyActivities.suspendIndexingAndRun(DumbServiceHeavyActivities.java:21)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:187)
	at com.pestphp.pest.services.ExpectationFileService.generateFile$lambda-6$lambda-5(ExpectationFileService.kt:78)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.pestphp.pest.services.ExpectationFileService.generateFile$lambda-6(ExpectationFileService.kt:77)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.
```

**Comment by olivernybroe** [comment]
Hi, thank you for reporting this. A rework of the feature which is giving you this error is currently being worked on. 

It is related to #177.

**Comment by olivernybroe** [comment]
I have a fix ready in the current EAP. 
I will wait with releasing it until we have had it running in EAP for a while, to make sure the solution actually works for all.

You can install it via the EAP channel or install it manually
https://github.com/pestphp/pest-intellij#installation

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.2.0-EAP.2.zip](https://github.com/pestphp/pest-intellij/files/7234566/PEST.PHP-1.2.0-EAP.2.zip)
