### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.project.DumbService because container is already disposed (container=Project(name=cafincloud.it, containerState=DISPOSE_COMPLETED, componentStore=/Users/loiaconoa/root_web/cafincloud.it) (disposed))

### ISSUE THREAD

**Issue by loiaconoa** [pestphp/pest-intellij#186]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.5
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Mac OS X

### Stacktrace
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.project.DumbService because container is already disposed (container=Project(name=cafincloud.it, containerState=DISPOSE_COMPLETED, componentStore=/Users/loiaconoa/root_web/cafincloud.it) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:125)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:612)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.project.DumbService.getInstance(DumbService.java:197)
	at com.pestphp.pest.services.ExpectationFileService.generateFile$lambda-6$lambda-5(ExpectationFileService.kt:78)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.pestphp.pest.services.ExpectationFileService.generateFile$lambda-6(ExpectationFileService.kt:77)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueu
```

**Comment by olivernybroe** [comment]
Hi, thank you for reporting the bug, this bug is actually related to #177 which I am currently working on a rewrite to fix.

**Comment by olivernybroe** [comment]
I have a fix ready in the current EAP. 
I will wait with releasing it until we have had it running in EAP for a while, to make sure the solution actually works for all.

You can install it via the EAP channel or install it manually
https://github.com/pestphp/pest-intellij#installation

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.2.0-EAP.2.zip](https://github.com/pestphp/pest-intellij/files/7234566/PEST.PHP-1.2.0-EAP.2.zip)
