### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by crezra** [pestphp/pest-intellij#197]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.2.0
| Pest version     | x.y.z
| IntelliJ version | PS-212.5284.49
| OS               | Mac OS X

### Stacktrace
```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:821)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:773)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:501)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:305)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:574)
	at com.jetbrains.php.PhpIndexImpl.lambda$getFunctionsByName$12(PhpIndexImpl.java:522)
	at com.jetbrains.php.PhpIndexImpl.getCached(PhpIndexImpl.java:503)
	at com.jetbrains.php.PhpIndexImpl.getFunctionsByName(PhpIndexImpl.java:521)
	at com.jetbrains.php.PhpIndexImpl.getFunctionsByFQN(PhpIndexImpl.java:530)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:723)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:649)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.decodeExtendedClassesAndSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:113)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.getExtendedClassesToSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:89)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.complete(PhpGenericsBaseExtendedWithGenericTypeProvider.java:67)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:158)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:158)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:115)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:94)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:688)
	at com.pestphp.pest.customExpectations.generators.ExpectationGenerator.methodString(ExpectationGenerator.kt:32)
	at com.pestphp.pest.customExpectations.generators.ExpectationGenerator.access$methodString(ExpectationGenerator.kt:11)
	at com.pestphp.pest.customExpectations.generators.ExpectationGenerator$generate$1.invoke(ExpectationGenerator.kt:16)
	at com.pestphp.pest.customExpectations.generators.ExpectationGenerator$generate$1.invoke(ExpectationGenerator.kt:16)
	at kotlin.text.StringsKt__AppendableKt.appendElement(A
```

**Comment by qwertywelch** [comment]
Installed the 1.2.1 EAP and error has not re-occurred! Thanks, @olivernybroe.

**Comment by olivernybroe** [comment]
Amazing! Thanks for testing it out @qwertywelch. 

I'll wait a couple of days and then release v.1.2.1 with this fix then 👍
