### ISSUE TITLE
Slow operations on EDT caused by location provider

### ISSUE THREAD

**Issue by leMaur** [pestphp/pest-intellij#208]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.2.1
| Pest version     | x.y.z
| IntelliJ version | PS-213.5281.20
| OS               | Mac OS X

### Stacktrace
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:102)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:784)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:244)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:349)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:318)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:223)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:210)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:57)
	at com.jetbrains.php.util.pathmapper.PhpLocalPathMapper.lambda$getLocalPath$0(PhpLocalPathMapper.java:73)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.jetbrains.php.util.pathmapper.PhpLocalPathMapper.getLocalPath(PhpLocalPathMapper.java:73)
	at com.jetbrains.php.util.pathmapper.PhpLocalPathMapper.getLocalFile(PhpLocalPathMapper.java:98)
	at com.pestphp.pest.configuration.PestLocationProvider.getLocationInfo(PestLocationProvider.kt:57)
	at com.pestphp.pest.configuration.PestLocationProvider.getLocation(PestLocationProvider.kt:38)
	at com.intellij.execution.testframework.sm.runner.SMTestLocator.getLocation(SMTestLocator.java:57)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$CombinedTestLocator.getLocation(SMTestRunnerConnectionUtil.java:247)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.lambda$computeLocation$4(SMTestProxy.java:334)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:368)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.computeLocation(SMTestProxy.java:333)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.lambda$getLocation$2(SMTestProxy.java:316)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedVa
```

**Comment by olivernybroe** [comment]
Not able to reproduce it. 

@leMaur does this error still happen for you? If yes, try updating the EAP to the newest version, e.g. `PS-213.5449.28`. If it still gives you issues I'll reopen this.

**Comment by leMaur** [comment]
@olivernybroe I've updated the EAP to the latest version! I'll let you know if this error happen again..
Thanks for now
