### ISSUE TITLE
Slow operations on EDT caused by custom expectations generator

### ISSUE THREAD

**Issue by jk** [pestphp/pest-intellij#210]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.2.1
| Pest version     | 1.20.0
| IntelliJ version | PS-213.5281.20
| OS               | Mac OS X

### Description
Did nothing, just started the phpStorm EAP version with activated pest plugin.

### Stacktrace
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:102)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:784)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:514)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:318)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:592)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1010)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:985)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1070)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1064)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1107)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:744)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:680)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:667)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.decodeExtendedClassesAndSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:160)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.decodeExtendedClassesAndSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:125)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.getExtendedClassesToSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:118)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.complete(PhpGenericsBaseExtendedWithGenericTypeProvider.java:81)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:165)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:165)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:120)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:99)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:756)
	at com.pestphp.pest.customExpectations.generators.ExpectationGenerator.methodString(ExpectationGenerator.kt:32)
	at com.pestphp.pest.customExpectations.generators.ExpectationGenerator.access$methodString(ExpectationGenerator.kt:11)
	at com.pestphp.pest.customExpectations.generators.ExpectationGenerator$generate$1.invoke(E
```

**Comment by olivernybroe** [comment]
Thanks for reporting this, having some trouble reproducing, as this exception does not happen for me on the EAP. 

Could you include the full stacktrace as the one here is truncated? (github does not allow copying that much text)

**Comment by jk** [comment]
@olivernybroe Sure, what do I have to do, to get the full stracktrace and post it here?

**Comment by olivernybroe** [comment]
@jk When the error occurs, the same place where you send the exception to here. There is a stacktrace in there. 
Just copy/paste that in 👍

**Comment by jk** [comment]
Looks like I'm unable to reproduce it. Even un- and reinstalling the plugin didn't provoke the exception anymore. I will copy the fullstack on the next encounter, if any.

**Comment by olivernybroe** [comment]
@jk Alright, might be a hickup in the EAP, I'll close this then and reopen if it happens for you again 👍 

Thanks for reporting!
