### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by atymic** [pestphp/pest-intellij#237]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.2.1
| Pest version     | x.y.z
| IntelliJ version | PS-212.5457.49
| OS               | Mac OS X

### Stacktrace
```
java.lang.NullPointerException
	at com.pestphp.pest.PestUtilKt.isPestFile(PestUtil.kt:83)
	at com.pestphp.pest.PestIconProvider.findIconFromPsiFile(PestIconProvider.kt:29)
	at com.pestphp.pest.PestIconProvider.access$findIconFromPsiFile(PestIconProvider.kt:10)
	at com.pestphp.pest.PestIconProvider$getIcon$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.pestphp.pest.PestIconProvider.getIcon(PestIconProvider.kt:37)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:88)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:84)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:84)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:297)
	at com.intellij.diagram.components.ScalableIconWrapper.evaluateDeferred(ScalableIconWrapper.java:112)
	at com.intellij.diagram.components.ScalableIconWrapper.evaluateDeferredAndWrap(ScalableIconWrapper.java:106)
	at com.intellij.diagram.components.DiagramNodeHeaderComponent.createLabel(DiagramNodeHeaderComponent.java:45)
	at com.intellij.diagram.components.DiagramNodeHeaderComponent.<init>(DiagramNodeHeaderComponent.java:36)
	at com.intellij.diagram.components.DiagramNodeContainer.<init>(DiagramNodeContainer.java:133)
	at com.intellij.diagram.extras.DiagramExtras.createNodeComponent(DiagramExtras.java:123)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.lambda$tuneNode$3(DefaultUmlRenderer.java:69)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.tuneNode(DefaultUmlRenderer.java:67)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.tuneNode(DefaultUmlRenderer.java:59)
	at com.intellij.openapi.graph.builder.renderer.AbstractColoredNodeCellRenderer.getRendererComponent(AbstractColoredNodeCellRenderer.java:57)
	at com.intellij.uml.core.renderers.DefaultUmlRenderer.getRendererComponent(DefaultUmlRenderer.java:84)
	at com.intellij.openapi.graph.builder.renderer.BasicNodeCellRenderer.getNodeCellRendererComponent(BasicNodeCellRenderer.java:54)
	at com.intellij.openapi.graph.builder.util.GraphViewUtil.setRenderedNodeSizes(GraphViewUtil.java:163)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.updateNodeRealizer(GraphBuilderImpl.java:266)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.updateRealizers(GraphBuilderImpl.java:255)
	at com.intellij.uml.UmlGraphBuilder.updateRealizers(UmlGraphBuilder.java:244)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.updateView(GraphBuilderImpl.java:239)
	at com.intellij.opena
```

**Comment by olivernybroe** [comment]
Thanks for reporting, it is fixed in main branch and a new version will be out in a couple of days.
