### ISSUE TITLE
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by jakublabno** [pestphp/pest-intellij#307]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.1
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Linux

### Stacktrace
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:110)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:754)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:244)
	at com.intellij.util.indexing.FileBasedIndexEx.collectFileIdsContainingAllKeys(FileBasedIndexEx.java:512)
	at com.intellij.util.indexing.FileBasedIndexEx.processFilesContainingAllKeysInPhysicalFiles(FileBasedIndexEx.java:385)
	at com.intellij.util.indexing.FileBasedIndexEx.processFilesContainingAllKeys(FileBasedIndexEx.java:413)
	at com.intellij.psi.impl.cache.impl.IndexCacheManagerImpl.processVirtualFilesWithAllWords(IndexCacheManagerImpl.java:83)
	at com.intellij.psi.impl.cache.impl.IndexCacheManagerImpl.collectVirtualFilesWithWord(IndexCacheManagerImpl.java:99)
	at com.intellij.psi.impl.cache.impl.IndexCacheManagerImpl.processFilesWithWord(IndexCacheManagerImpl.java:106)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processAllFilesWithWord(PsiSearchHelperImpl.java:666)
	at com.pestphp.pest.startupActivity.ExpectationFileStartupActivity.runActivity$lambda-1(ExpectationFileStartupActivity.kt:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:828)
	at com.pestphp.pest.startupActivity.ExpectationFileStartupActivity.runActivity(ExpectationFileStartupActivity.kt:23)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:268)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.kt:247)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivity(StartupManagerImpl.kt:59)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:222)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:401)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:393)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intel
```

**Comment by olivernybroe** [comment]
Hi, you are running a very old version of the plugin. Please update to the newest version.
