### ISSUE TITLE
this error keep showing

### ISSUE THREAD

**Issue by cobraprojects** [pestphp/pest-intellij#408]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.8.3
| Pest version     | x.y.z
| IntelliJ version | PS-222.4459.28
| OS               | Linux

### Description
<FILL OUT THE DESCRIPTION>

### Stacktrace
`java.lang.Throwable: Stub ids not found for key in index = php.class.shortName, file = file:///mnt/d/Work/laragon/www/rabta/vendor/nesbot/carbon/src/Carbon/Traits/Mutability.php, file type = com.jetbrains.php.lang.PhpFileType@327bfec1, indexed file type = com.jetbrains.php.lang.PhpFileType@327bfec1`

```
java.lang.Throwable: Stub ids not found for key in index = php.class.shortName, file = file:///mnt/d/Work/laragon/www/rabta/vendor/nesbot/carbon/src/Carbon/Traits/Mutability.php, file type = com.jetbrains.php.lang.PhpFileType@327bfec1, indexed file type = com.jetbrains.php.lang.PhpFileType@327bfec1
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:65)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:178)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:177)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:659)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1111)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1086)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1172)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1166)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1209)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.findSuper(PhpType.java:909)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.findSuper(PhpType.java:887)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.isConvertibleFrom(PhpType.java:803)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.isConvertibleFrom(PhpType.java:740)
	at com.pestphp.pest.features.customExpectations.ExpectationUtilKt.isExpectation(expectationUtil.kt:28)
	at com.pestphp.pest.inspections.MultipleExpectChainableInspection$buildVisitor$1.visitPhpGroupStatement(MultipleExpectChainableInspection.kt:25)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:22)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:317)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:325)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:331)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:294)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:294)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:297)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:282)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:270)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by olivernybroe** [comment]
Try clearing your indexes and see if the error goesaway.
