### ISSUE TITLE
com.intellij.psi.stubs.ManyProjectsStubIndexMismatch: PSI and index do not match.

### ISSUE THREAD

**Issue by jacklogic13** [pestphp/pest-intellij#473]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.3
| Pest version     | x.y.z
| IntelliJ version | PS-231.9011.38
| OS               | Windows 10

### Stacktrace
```
com.intellij.psi.stubs.ManyProjectsStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PHP file, file.class=class com.jetbrains.php.lang.psi.PhpFileImpl, file.lang=Language: PHP, modStamp=1
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
 viewProvider=com.jetbrains.php.lang.PhpFileViewProvider{vFile=file://D:/myData2/mnt/var/www/vhosts/v5.marketmenow.co.uk/codebase/5.0.0/vendor/Expectation.php, vFileId=105048, content=VirtualFileContent{size=260}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1687247114192; file length: 260
 doc saved: true; doc stamp: 0; doc size: 0; committed: true
indexing info: indexing timestamp = 1687247114192, binary = false, byte size = 260, char size = 260
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PhpFileStubImpl}291998128
   same size=false
   debugInfo=created from index; with backReference
	at com.intellij.psi.stubs.StubTreeLoader.handleManyProjectsMismatch(StubTreeLoader.java:224)
	at com.intellij.psi.stubs.StubTreeLoader.access$000(StubTreeLoader.java:28)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:209)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.lambda$createCompleteException$0(StubTreeLoader.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.createCompleteException(StubTreeLoader.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:230)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:745)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:948)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:755)
	at com.pestphp.pest.ExpectUtilKt.getExpectExtends(ExpectUtil.kt:85)
	at com.pestphp.pest.fileListeners.ExtendAsyncFileListener.updateFile(ExtendAsyncFileListener.kt:38)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$prepareChange$listener$1.updateFile(AsyncFileChangeListenerBase.kt:33)
	at com.intellij.openapi.externalSystem.autoimport.changes.vfs.VirtualFileChangesSeparator.processFile(VirtualFileChangesSeparator.kt:34)
	at com.intellij.openapi.externalSystem
```

**Comment by olivernybroe** [comment]
Old version.
